import React, { Component } from 'react';
import './App.css';
import Input from './components/Input';

class App extends Component {
  state = {
    input: "",
    indicator: "",
    indicator2: "",
    trial: 3,
    prevInput: "",
    randNum: Math.floor((Math.random() * 100) + 1)
  }

  checkInput = (e) => {
    e.preventDefault()
    this.setState({input: ""});

    let {input, trial, prevInput} = this.state;
    this.setState({prevInput: input});

    if (input !== this.state.randNum) {
      this.setState({indicator: "Wrong answer"});

      setTimeout(()=>{
        this.setState({indicator: ""});
      }, 2000)

      if (input !== prevInput) {
        this.setState({trial: trial-1});
        if(trial === 0) {
          this.setState({indicator2: "You lose"});
          this.setState({trial: 3});
        }
      }
    }else{
      this.setState({indicator: "Correct!"});
      setTimeout(() => {
        this.setState({indicator: ""});
        setTimeout(() => {
          this.setState({randNum: Math.floor((Math.random() * 100) + 1)});
        }, 1000)
      }, 2000);
    }

  }

  onChange = (e)=>{
    let guess = Math.trunc(e.target.value);
    this.setState({input: guess});
  }

  restart = (e) => {
    e.preventDefault()

    this.setState({input: ""});
    this.setState({trial: 3});
    this.setState({indicator: ""});
    this.setState({indicator2: ""});
    this.setState({prevInput: ""});
    this.setState({randNum: Math.floor((Math.random() * 100) + 1)});
  }
  render(){
    return (
      <div className="App">
        <h1 style={{textAlign: "center"}}>GUESS THE NUMBER!</h1>
        <p>
          <h3>Instruction:</h3>
          You are expected to guess the right number  generated by the computer.
          You only have 3 trials in the game.
        </p>
        <h2>{this.state.indicator2}</h2>
        <h2>{this.state.indicator}</h2>
        <h2>Trial: {this.state.trial}</h2>
        <Input state={this.state.input} check={this.checkInput} onChange={this.onChange}/>
        <button type="button" onClick={this.restart}>Restart</button>
      </div>
    );
  }
 
}

export default App;
